services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=America/Sao_Paulo
    ports:
      - "8191:8191"
    restart: unless-stopped

  postgres:
    image: bitnami/postgresql:latest
    container_name: ms-tibia-trade-check-postgres
    environment:
      POSTGRES_USER: tibia_user
      POSTGRES_PASSWORD: tibia_password
      POSTGRES_DB: tibia_trade
    ports:
      - "5435:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  # rabbitmq:
  #   image: rabbitmq:4-management
  #   container_name: rabbitmq
  #   environment:
  #     RABBITMQ_DEFAULT_USER: tibia_user
  #     RABBITMQ_DEFAULT_PASS: tibia_password
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   volumes:
  #     - rabbitmq-data:/var/lib/rabbitmq
  #   restart: unless-stopped

volumes:
  postgres-data:
  # rabbitmq-data:
